apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supportservice-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:hostingsolutions/support-services.git
    targetRevision: develop
    path: staging/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: false