apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supportservice-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:hostingsolutions/support-services.git
    targetRevision: HEAD
    path: prod/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod